### ISSUE TITLE
Manual installation is wrong

### ISSUE THREAD

**Issue by omrisarig13** [chamindra/marvim#11]
The explanation in the readme for how to install the plugin manually is wrong.
It still assumes that the plugin is a single file, and since it is not a single file any more this installation won't work.

**Comment by chamindra** [comment]
I have tested the merge for the manual installation post vim 8 and it works.

**Comment by chamindra** [comment]
Saw the updated one and agree with that.

Chamindra de Silva
https://www.linkedin.com/in/chamindra |
http://chamindra-de-silva.blogspot.com
