### ISSUE TITLE
 g:marvim_store does not work for absolute paths

### ISSUE THREAD

**Issue by chamindra** [chamindra/marvim#13]
Tested the marvim_store location with a few different locations 
i.e. let g:marvim_store = '/usr/local/.marvim' " change store place.
It works for the default ~/.mavim and if you just give a name like 'marvim.kb', but relative paths from home and absolute paths do not seem to work anymore. This is a known defect that needs to be fixed

**Comment by omrisarig13** [comment]
@chamindra - 
There was indeed a bug when expanding paths containing the '~' character. The path was not expanded, so the path turn to be wrong. I created a branch that fixes this issue, it is called "fix_store_path_bug".

However, I could not reproduce the bug about absolute paths. When I save absolute path in the path of g:marvim_store, it works on my setup. Can you be more specific about when exactly it happens?
